version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
    runas: ubuntu
hooks:
  BeforeInstall:
      - location: config/scripts/before_install.sh
  AfterInstall:
      - location: config/scripts/after_install.sh