# Generated by Django 4.0.3 on 2022-04-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_tag_alter_note_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tag',
        ),
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.ManyToManyField(to='notes.tag'),
        ),
    ]
